### ISSUE TITLE
How to set canvas size

### ISSUE THREAD

**Issue by sbuys** [williamngan/react-pts-canvas#1]
Any way to set the canvas size?

**Comment by williamngan** [comment]
Hi @sbuys , usually you can set the `name` prop, and reference its class name in your css file to set its width and height.

But I realized it's sometimes inconvenient -- so I just pushed a change to take a `style` prop, which you can use to set custom style attributes. Update to v0.1.2 to use the `style` prop.

So to recap, there're two ways:
1. `<Example name="hello" />` and then set css rules like `.hello { width: 100px }`
2. `<Example style={{width: 100}} />`

If needed, you can also set the style of `<canvas>` directly via `canvasStyle` prop or via referencing class name `.hello-canvas` in your css file. 
 
Hope this helps :)

**Comment by sbuys** [comment]
Thanks @williamngan ! This is great.
