### ISSUE TITLE
React hooks / functional components? 

### ISSUE THREAD

**Issue by tony** [williamngan/react-pts-canvas#15]
Is there any roadmap or interest in supporting `useX`-style / react hook functions with this?

Over the past year I've began using functional components more to control components. Though not quite sure whether or not `PtsCanvas` could be extrapolated to hooks yet.

**Comment by williamngan** [comment]
Hi @tony - it would be a great option, but I've lost track of the latest and greatest of React.

Would you be interested in building it?

**Comment by tony** [comment]
@williamngan First thank you for letting it be known you're open to hooks / FC in this project.

I'm not at the exact point where I can do that. If I get there, I can make it known. Or, someone else who reads this can, if they get to it before me!

**Comment by tibotiber** [comment]
Hi @tony, in case you were getting started on this, feel free to ping me and I'll do my best to support with ideas / feedback, code review, and testing in a production app :). Cheers.

**Comment by tony** [comment]
@tibotiber Thank you

If you are interested feel free to take this up in my place. If not, anyone else can feel free to PR this as a change

At the moment I have a bit too much on my plate (sorry about that!)

**Comment by tibotiber** [comment]
Absolutely no worries, most of us are in the "busy boat" these days ;). The offer is good for anyone taking this up of course.

**Comment by barshopen** [comment]
Hi :) Is anyone actively working on making functional components available?

**Comment by tibotiber** [comment]
Not on my end, I think it's for grab ;)

**Comment by tony** [comment]
It's up to grab for sure. :) 

I ended up not needing a canvas library... but there are other TypeScript ones these days to look at for reference. https://github.com/pixijs/pixi.js, https://github.com/projectstorm/react-canvas, https://github.com/canvg/canvg

https://github.com/search?l=TypeScript&p=1&q=canvas&type=Repositories

So there's room to cooperate between this project and the others if there is commonality

**Comment by prkirby** [comment]
Hey Everyone, 

I made a rough PR that refactors PtsCanvas into a functional component. @tony or @tibotiber If either of you are interested in taking a look and letting me know what you think / comments, that would be great. 

@williamngan let me know if this is something you want in the repo. There is a good bit of clean up, like updating the examples, etc, just want to make sure its a wanted refactor first. 

I used this in a personal project and everything is working great. 

PR -> #32

**Comment by williamngan** [comment]
Thanks for the PR, @prkirby ! I'm a bit rusty on the latest of React, but I'll take a look. If @tibotiber or @tony can review the PR, that would be very much appreciated too. 🙏  Cheers!

**Comment by tibotiber** [comment]
Hey, nice PR! I'm on Chinese New Year break at the moment but I'll have a look at this once I get back to work — in the coming week or two. I'll also pull your PR as dependency in my (sizable) app and see if anything breaks. Cheers.

**Comment by williamngan** [comment]
Functional component is here in v0.3 -- thanks to @prkirby's PR! Closing this now.
