### ISSUE TITLE
Making sure a space is fully disposed when unmounting

### ISSUE THREAD

**Issue by tibotiber** [williamngan/react-pts-canvas#17]
Hi @williamngan,

This is a follow up to #16 for which I'll post a PR in a minute.

Zooming out from that specific issue, I'm wondering if there are other things that should be removed when unmounting: event listeners, bound methods, animation requests, others?. Maybe `space` should have a `dispose` method? This is to ensure that applications which open/close the canvas many times do not suffer bad performance. 

I am motivated to make the PRs for this but might need your guidance to know where are potential performance issues / handlers leaks. Not sure if there is anything at all (do you know of a way to debug that easily?), but worth stopping to think about it I guess.

What do you think?

Also this might be better listed in the pts repo, let me know if you want to change that.

**Comment by williamngan** [comment]
Thank you so much @tibotiber !

I actually really like your suggestion on a `space.dispose` method. Then we can have a single function to manage these. If you can send a PR to Pts repo, that would be awesome 🙏 

I think there's only a `resize` event which we need to take care of. There are a couple of mouse & touch events which are attached to canvas element, but they should be removed automatically when the element unmounts, right?

**Comment by tibotiber** [comment]
Yes, I guess they should be removed as well. What about the animation frame request in `play()`, would that need to be cancelled or is it done already?

**Comment by tibotiber** [comment]
PR opened :)

**Comment by williamngan** [comment]
Thanks @tibotiber for the PR. I've patched pts to 0.9.3 and react-pts-canvas to 0.2.8. See if that works 😃

**Comment by tibotiber** [comment]
@williamngan I've updated to the latest versions and it now works as intended in my app :). Good to close. Thanks for your feedback on this. 🍻
