### ISSUE TITLE
Dependency tree broken, react ver 17.

### ISSUE THREAD

**Issue by Asilver-jpg** [williamngan/react-pts-canvas#64]
Only seems to work with react 15 or 16, can we get this to work with 17 or should we just force it to install?

**Comment by prkirby** [comment]
@williamngan this is addressed in my pr #32 FYI

**Comment by Asilver-jpg** [comment]
Horay!!!!!

**Comment by williamngan** [comment]
@Asilver-jpg This should be fixed in v0.3.0. Thanks to @prkirby for the awesome PR!
