### ISSUE TITLE
Play get called twice?

### ISSUE THREAD

**Issue by williamngan** [williamngan/react-pts-canvas#70]
After fixing a replay issue, I found that [`maybePlay`](https://github.com/williamngan/react-pts-canvas/blob/master/src/index.tsx#L143) get called twice after a state change in the parent component.

Repro:
1. run the `example` and click the Play/Stop button on top-left
2. Edit [`maybePlay`](https://github.com/williamngan/react-pts-canvas/blob/master/src/index.tsx#L143) with console.log
```jsx
const maybePlay = () => {
    const space = spaceRef.current
    if (!space) return
    if (play) {
      if (space.isPlaying) {
        space.resume()
        console.log('resume!')
      } else {
        space.replay() // if space has stopped, replay
        console.log('replay')
      }
    } else {
      space.pause(true)
      console.log('pause!')
    }
  }
```
3. See that console.log get 'pause!' and 'resume!' on a single click

**Comment by williamngan** [comment]
Do you have time to take a look, @prkirby ? :)

**Comment by prkirby** [comment]
@williamngan which example sorry?

**Comment by williamngan** [comment]
Sorry for the confusion - I meant the example in the [example](https://github.com/williamngan/react-pts-canvas/tree/master/example) folder.

**Comment by prkirby** [comment]
Interesting. I'm looking through it now @williamngan. One thing I found is that if instead of using the button, I simply change the props value using the react dev tools, maybePlay does only fire once.

**Comment by prkirby** [comment]
@williamngan Ahh, ok. So since the state is in the App component, its triggering a re-render for all child components when the state updates. This was a good read: https://felixgerschau.com/react-rerender-components/

So the fix would be to include the button in the actual example component, or a wrapper component around it, rather than in the Parent where its going to trigger a re-render for both examples.

**Comment by williamngan** [comment]
Wow this is really nuanced. Thanks for looking into it, @prkirby !
