### ISSUE TITLE
Invalid use of useLayoutEffect in SSR-env

### ISSUE THREAD

**Issue by tom-bywild** [williamngan/react-pts-canvas#77]
### Description

When using `react-pts-canvas` in a setup w/ SSR-rendering (e.g. Next.js), the usage of `useLayoutEffect` causes an issue as the hook is only allowed to run on the client. Subsequently, a warning is logged to the console.

The line causing the issue is [here](https://github.com/williamngan/react-pts-canvas/blob/master/src/index.tsx#L85).

### Solution

`useLayoutEffect` should only be used on the client, therefore an isomorphic variant is required that runs safely on both client + server. [Example of an existing package](https://github.com/Andarist/use-isomorphic-layout-effect/blob/main/src/index.ts). As the change is basically a one-liner, I wouldn't propose to use a package but rather implement it directly.

I would be grateful to work on it.

### Repo to reproduce

- https://github.com/flaming-codes/react-pts-canvas-ssr-layout-effect-issue

### Screenshots

|Description|Image|
|---|---|
|Warning log | ![Screenshot 2022-05-24 at 22 05 57](https://user-images.githubusercontent.com/102795185/170124138-b0d77ee8-06d1-40f5-ba32-d785449829ab.png) |

**Comment by williamngan** [comment]
Hi @tom-bywild -- sorry I missed this issue until now. Would you be interested in sending a PR?

**Comment by flaming-codes** [comment]
Hi @williamngan No problem! Sure, will do that later today.

**Comment by tom-bywild** [comment]
@williamngan PR is ready for review

**Comment by williamngan** [comment]
Thank you so much! Patched in v0.3.4.
